apiVersion: apps/v1
kind: Deployment
metadata:
  name: telecom-selling-expert-admin-frontend-vue
  labels:
    app: telecom-selling-expert-admin-frontend-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telecom-selling-expert-admin-frontend-vue
  template:
    metadata:
      labels:
        app: telecom-selling-expert-admin-frontend-vue
    spec:
      containers:
        - name: telecom-selling-expert-admin-frontend-vue-service
          image: 172.22.121.50/speech-train/telecom-selling-expert-admin-frontend-vue:$CI_PIPELINE_IID
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: telecom-selling-expert-admin-frontend-vue-service
spec:
  type: NodePort
  selector:
    app: telecom-selling-expert-admin-frontend-vue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
